# Generated by Django 4.2.7 on 2026-08-19 09:21

from django.db import migrations, models
import django.db.models.deletion
import website_content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website_content.menu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=website_content.models.get_upload_path, validators=[website_content.models.validate_file_size])),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='website_content.menu')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['menu'], name='website_con_menu_id_7e53a9_idx'), models.Index(fields=['name'], name='website_con_name_c131de_idx'), models.Index(fields=['is_active'], name='website_con_is_acti_2fc24f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='website_con_name_566c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['is_active'], name='website_con_is_acti_cd6f77_idx'),
        ),
    ]
