# Generated by Django 4.2.7 on 2026-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
