# Generated by Django 4.2.7 on 2026-08-20 11:53

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0002_websitecontent_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
