# Generated by Django 4.2.7 on 2026-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0003_alter_websitecontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
