# Generated by Django 4.2.7 on 2026-08-18 18:34

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbshe_student_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='e.g., CS01, MATH101', max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('academic_year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=20)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='sbshe_student_portal.course')),
            ],
            options={
                'ordering': ['academic_year', 'semester', 'subject_code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('syllabus', 'Syllabus'), ('study_material', 'Study Material'), ('question_paper', 'Question Paper'), ('assignment', 'Assignment'), ('assessment', 'Assessment'), ('lecture_notes', 'Lecture Notes'), ('lab_manual', 'Lab Manual'), ('reference', 'Reference Material')], help_text='Type of material', max_length=50)),
                ('title', models.CharField(help_text='Title of the material', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(help_text='Upload material file (max 10MB)', upload_to=materials.models.subject_material_file_path, validators=[materials.models.validate_file_extension, materials.models.validate_file_size])),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.subject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['subject'], name='materials_s_subject_9c158b_idx'), models.Index(fields=['material_type'], name='materials_s_materia_91b337_idx'), models.Index(fields=['is_active'], name='materials_s_is_acti_b184ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_code'], name='materials_s_subject_8e7870_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_name'], name='materials_s_subject_f39257_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['slug'], name='materials_s_slug_87ea33_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course'], name='materials_s_course__ca6719_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['academic_year'], name='materials_s_academi_259859_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester'], name='materials_s_semeste_0dfecd_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='materials_s_is_acti_437f33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('course', 'subject_code')},
        ),
    ]
