# Generated by Django 4.2.7 on 2026-08-19 06:53

from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_subject_8e7870_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_subject_f39257_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_slug_87ea33_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_course__ca6719_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_academi_259859_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_semeste_0dfecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='materials_s_is_acti_437f33_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectmaterial',
            name='materials_s_subject_9c158b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectmaterial',
            name='materials_s_materia_91b337_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectmaterial',
            name='materials_s_is_acti_b184ae_idx',
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(upload_to=materials.models.subject_material_file_path, validators=[materials.models.validate_file_extension, materials.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='material_type',
            field=models.CharField(choices=[('syllabus', 'Syllabus'), ('study_material', 'Study Material'), ('question_paper', 'Question Paper'), ('assignment', 'Assignment'), ('assessment', 'Assessment')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmaterial',
            unique_together={('subject', 'material_type')},
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='title',
        ),
    ]
