# Generated by Django 4.2.7 on 2026-08-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_subject_materials_s_subject_8e7870_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectmaterial',
            unique_together=set(),
        ),
    ]
