# Generated by Django 4.2.7 on 2026-08-24 11:31

from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_subjectmaterial_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(max_length=500, upload_to=materials.models.subject_material_file_path, validators=[materials.models.validate_file_extension, materials.models.validate_file_size]),
        ),
    ]
