# Generated by Django 4.2.7 on 2026-08-17 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sbshe_student_portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('introduction', models.TextField(help_text='Brief introduction about the department')),
                ('file', models.FileField(blank=True, help_text='Department image/photo or PDF (max 10MB)', null=True, upload_to=sbshe_student_portal.models.department_file_path, validators=[sbshe_student_portal.models.validate_image_or_pdf, sbshe_student_portal.models.validate_image_or_pdf_size])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sbshe_stude_name_cc6792_idx'), models.Index(fields=['is_active'], name='sbshe_stude_is_acti_05bd85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('introduction', models.TextField(help_text='Rich text supported')),
                ('full_description', models.TextField(help_text='Detailed course description')),
                ('course_code', models.CharField(blank=True, help_text='Course code (e.g., CS101)', max_length=100, null=True, unique=True)),
                ('file', models.FileField(blank=True, help_text='Course image/thumbnail or PDF (max 10MB)', null=True, upload_to=sbshe_student_portal.models.course_file_path, validators=[sbshe_student_portal.models.validate_image_or_pdf, sbshe_student_portal.models.validate_image_or_pdf_size])),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 Years, 6 Months, 120 Hours', max_length=100, null=True)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria for the course', null=True)),
                ('course_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid (Online + Offline)')], default='offline', help_text='Course delivery mode', max_length=20)),
                ('is_top_course', models.BooleanField(default=False, help_text='Mark as top/popular course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='sbshe_student_portal.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, help_text='Branch image/photo or PDF (max 10MB)', null=True, upload_to=sbshe_student_portal.models.branch_file_path, validators=[sbshe_student_portal.models.validate_image_or_pdf, sbshe_student_portal.models.validate_image_or_pdf_size])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sbshe_stude_name_57d6be_idx'), models.Index(fields=['location'], name='sbshe_stude_locatio_216303_idx'), models.Index(fields=['is_active'], name='sbshe_stude_is_acti_4d9cba_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, help_text='Course code (auto-filled from course)', max_length=100, null=True)),
                ('material_type', models.CharField(choices=[('assignment', 'Assignment'), ('question_paper', 'Question Paper'), ('syllabus', 'Syllabus')], default='assignment', help_text='Type of material (Assignment, Question Paper, Syllabus)', max_length=20)),
                ('subject_code', models.CharField(blank=True, help_text='Subject code (e.g., CS101, MATH201) - Manually entered by admin', max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], help_text='Academic year (e.g., First Year, Second Year, etc.)', max_length=20, null=True)),
                ('title', models.CharField(help_text='Title of the material', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description (optional)', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions (optional)', null=True)),
                ('file', models.FileField(blank=True, help_text='File (PDF or images: JPG, PNG, GIF, BMP, WEBP)', null=True, upload_to=sbshe_student_portal.models.material_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp']), sbshe_student_portal.models.validate_image_or_pdf_size])),
                ('deadline', models.DateField(blank=True, help_text='Deadline (applicable for assignments)', null=True)),
                ('semester', models.CharField(blank=True, help_text='Semester (e.g., 1st Semester, 2nd Semester)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='sbshe_student_portal.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course'], name='sbshe_stude_course__0b4f32_idx'), models.Index(fields=['course_code'], name='sbshe_stude_course__562ba7_idx'), models.Index(fields=['material_type'], name='sbshe_stude_materia_5db583_idx'), models.Index(fields=['subject_code'], name='sbshe_stude_subject_94be92_idx'), models.Index(fields=['academic_year'], name='sbshe_stude_academi_ac4e62_idx'), models.Index(fields=['is_active'], name='sbshe_stude_is_acti_74bb4c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='sbshe_stude_name_33707c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='sbshe_stude_departm_4d813a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='sbshe_stude_is_acti_427ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='sbshe_stude_slug_109930_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_top_course'], name='sbshe_stude_is_top__5f7f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='sbshe_stude_course__417e2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'name')},
        ),
    ]
