# Generated by Django 4.2.7 on 2026-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbshe_student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courier_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Courier charge in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hard_copy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for hard copy in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='soft_copy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for soft copy in INR', max_digits=10, null=True),
        ),
    ]
