# Generated by Django 4.2.7 on 2026-08-12 07:03

from django.db import migrations, models
import sbshe_student_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('sbshe_student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, help_text='Branch image/photo (max 5MB)', null=True, upload_to=sbshe_student_portal.models.branch_image_path, validators=[sbshe_student_portal.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid (Online + Offline)')], default='offline', help_text='Course delivery mode', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 3 Years, 6 Months, 120 Hours', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Eligibility criteria for the course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course image/thumbnail (max 5MB)', null=True, upload_to=sbshe_student_portal.models.course_image_path, validators=[sbshe_student_portal.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='course',
            name='is_top_course',
            field=models.BooleanField(default=False, help_text='Mark as top/popular course'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, help_text='Department image/photo (max 5MB)', null=True, upload_to=sbshe_student_portal.models.department_image_path, validators=[sbshe_student_portal.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_top_course'], name='sbshe_stude_is_top__5f7f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='sbshe_stude_course__417e2b_idx'),
        ),
    ]
