# Generated by Django 4.2.7 on 2026-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbshe_student_portal', '0002_branch_image_course_course_type_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course code (e.g., CS101)', max_length=100, null=True, unique=True),
        ),
    ]
