# Generated by Django 4.2.7 on 2026-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbshe_student_portal', '0002_course_courier_charge_course_hard_copy_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed course description', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction',
            field=models.TextField(blank=True, help_text='Rich text supported', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='introduction',
            field=models.TextField(blank=True, help_text='Brief introduction about the department', null=True),
        ),
    ]
