# Generated by Django 4.2.7 on 2026-08-20 11:53

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sbshe_student_portal', '0003_course_serial_number_department_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed course description', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text supported', null=True),
        ),
    ]
