# Generated by Django 4.2.7 on 2026-08-18 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbshe_student_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=255)),
                ('father_name', models.CharField(help_text="Father's full name", max_length=255)),
                ('email', models.EmailField(help_text="Student's email address", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(help_text='Phone number (10-15 digits)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(help_text='Complete address')),
                ('pincode', models.CharField(blank=True, help_text='Pincode (5-10 digits) - Optional', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be 5-10 digits', regex='^\\d{5,10}$')])),
                ('copy_type', models.CharField(choices=[('1', 'Soft Copy'), ('2', 'Hard Copy')], default='1', help_text='Select copy type', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_submitted', models.BooleanField(default=False, help_text='True when form is submitted')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the form was submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Select course', on_delete=django.db.models.deletion.CASCADE, related_name='student_forms', to='sbshe_student_portal.course')),
            ],
            options={
                'verbose_name': 'Student Form',
                'verbose_name_plural': 'Student Forms',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='student_form_email_idx'), models.Index(fields=['phone_number'], name='student_form_phone_idx'), models.Index(fields=['course'], name='student_form_course_idx'), models.Index(fields=['is_active'], name='student_form_active_idx'), models.Index(fields=['is_submitted'], name='student_form_submitted_idx')],
            },
        ),
    ]
